### PR TITLE
Added support for ZClassic. Also corrected BTG block explorer

### PR DESCRIPTION
**Pull request by StarbuckBG**
Please mind that I have used my address for ZCL dev fee. You can change it with yours. I have not tested the work of the pool for now, but will do soon.

### CODE REVIEW

**Comment by calvintam236** [comment]
1. Typo: `ZCassic`/`ZClassic` -> `Zclassic`
2. Make sure you have correct intent/ line ending at `CoinMetaData.cs`. I don't see much code changes for multiple line changes.

**Comment by oliverw** [comment]
@StarbuckBG As already stated by @calvintam236 please clean up CoinMetaData.cs. I don't want to see the entire file changing.

**Comment by StarbuckBG** [comment]
Ok Will do the changes. I have no idea why it changed the whole file.

**Comment by StarbuckBG** [comment]
I give up... I cannot understand what is the problem with this file and why it marks the file as completely changed ....

**Pull request merged**
