### PR TITLE
Florincoin -> Flo

### PR DESCRIPTION
**Pull request by bitspill**
Apply Flo re-branding to Miningcore

### CODE REVIEW

**Comment by oliverw** [comment]
@bitspill By the way, I have to revert the explorer link changes for flo since https://network.flo.cash has apparently no valid SSL cert.

**Comment by bitspill** [comment]
Oh. Sure does, seems it's still using the florincoin.info cert

**Comment by oliverw** [comment]
If this can be fixed rather quickly I'll keep your changes.

**Comment by bitspill** [comment]
I do not have access to the server running that explorer, I've pinged that team member but not sure how quickly they can get to it.

Alternatively there's this explorer https://livenet.flocha.in/

**Pull request merged**
