### PR TITLE
Update to latest ZCash Fundingstream

### PR DESCRIPTION
**Pull request by AlphaX-Projects**

### CODE REVIEW

**Comment by oliverw** [comment]
Does this PR equal compatibility with the current ZCash Mainnnet?

**Comment by AlphaX-Projects** [comment]
Yes, as current Zcash is changed to Fundingstream Payments

**Comment by oliverw** [comment]
Tested on Testnet?

**Comment by AlphaX-Projects** [comment]
And tested on on Realnet

**Comment by AlphaX-Projects** [comment]
Your Current Version will tell you missing Fundingstream Payments when block found

**Comment by oliverw** [comment]
Block unlock and payments also tested?

**Comment by AlphaX-Projects** [comment]
As i know nothing changed in unlock payment, only Foundersreward changed into Fundingstream

**Comment by AlphaX-Projects** [comment]
Anyway, we mined found blocks and all went normal

**Comment by oliverw** [comment]
Excellent job. Thank you for your contribution!

**Pull request merged**
