### PR TITLE
Add support for Zencash mining pool.

### PR DESCRIPTION
**Pull request by rterbush**
This is not yet ready to merge, but I would appreciate a review as to approach and any guidance as to what I may have missed. Will begin working on a testnet environment on my end in the meantime.

### CODE REVIEW

**Comment by oliverw** [comment]
@rterbush One question Randy, from the looks of it Zencash appears to be fully compatible to ZCash out of the box as most of the Zencash source files look identical to the ZCash sources. Did I miss something?

**Comment by rterbush** [comment]
@oliverw it is a ZEC fork, so not sure what level of overlap there is. There are different percentages for founders, etc. as well as the different addresses. I very likely made it harder than it needed to be...

**Comment by oliverw** [comment]
@rterbush First step would be to figure out possible founders or treasure rewards and add them to [this dictionary](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/ZCash/ZCashConstants.cs#L126).

After that I'd first try the easy route using <code>[CoinMetadata(CoinType.ZEC, CoinType.ZEN)]</code> and some mining against a testnet daemon for that currency.

**Comment by rterbush** [comment]
Will rework this and come back

**Pull request closed without merging**
