### PR TITLE
initial signalr integration WIP

### PR DESCRIPTION
**Pull request by Kukks**
This PR is not ready!

I'm working on adding a new notification method, a push from server to frontend via Signalr.  I'm a bit stuck since you opted out of using the standard IApplicationBuild and the default Service Collection DI. Not sure where I need to register and configure the SignalR startup. It is usually as follows:
```
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSignalR();
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseSignalR(routes =>
            {
                routes.MapHub<Chat>("chat");
            });
        }
    }
```

How should I go ahead @oliverw

### CODE REVIEW

**Comment by oliverw** [comment]
@Kukks Andrew there's actually no particular reason for not using the standard registration approach except it wasn't needed back then and I wanted to keep everything as lightweight as possible. If you need this I can re-instantiate the process.

**Comment by Kukks** [comment]
That would be good. :)

**Comment by Kukks** [comment]
Should I try to do it @oliverw ? I'm not as familiar with this setup though.

**Comment by oliverw** [comment]
I'll do it today.

**Comment by Kukks** [comment]
Just to clarify, would this mean you would remove Autofac DI as well as integrate the ApiServer back into the  actual bootstrap code?

**Comment by oliverw** [comment]
@Kukks Autofac will stay. I have experimented a lot with the .Net Core bootstrap and I've come to the conclusion that properly integrating the pipeline with a non-web .Net Core application will require this: https://github.com/aspnet/Hosting/pull/1204

I'm therefore postponing the boostrap change until .Net Core 2.1

**Comment by tutorialevideo** [comment]
Hi can you post a tutorial how to setup this pool?

**Pull request closed without merging**
