### PR TITLE
Added Api SSL Support

### PR DESCRIPTION
**Pull request by uurcm16**
Added SSL Support to Api Requests.
Added GZip Compression Support to Api Requests.

### CODE REVIEW

**Comment by oliverw** [comment]
@uurcm16 Thanks for the PR. What's the state of this PR. Is finished, tested and working?

**Comment by uurcm16** [comment]
> @uurcm16 Thanks for the PR. What's the state of this PR. Is finished, tested and working?

Sure yes. SSL is perfectly working on www.adaminers.com
I've tested the GZip compression on my local testnet. It works too.

**Comment by oliverw** [comment]
Does <code>ApiSSLConfig.SSLPath</code> point to a .pfx cert file?

**Comment by uurcm16** [comment]
Yes, SSLPassword is the password for the crt file

**Pull request merged**
