### PR TITLE
Custom Fee & Blacklist

### PR DESCRIPTION
**Pull request by belmix**
Add Custom Fee & Blacklist

### CODE REVIEW

**Comment by oliverw** [comment]
That's quite a lot of changes deep inside the payment system. I have think about this.

**Comment by belmix** [comment]
The use of this implementation is quite simple, by default there are three commissions.

rewardRecipients - percentage (stock Fee)
DevDonation.Percent (stock Fee)
+ percentageFeeDefault (add Fee)

Also by percentageFeeCustom we set an individual commission for miners address customFeeAddresses[]
If percentageFeeCustom 0 to 0.99 individual commission applies for customFeeAddresses[],  
if percentageFeeCustom = 1.0 customFeeAddresses[] is used as blacklist

the implementation does not affect the operation of the payment system, only complements it

**Comment by oliverw** [comment]
Did you verify that everything still works if none of the new options are used?

**Comment by oliverw** [comment]
@belmix See my last message.

**Comment by belmix** [comment]
I'll check this branche on the testnet tomorrow

**Comment by belmix** [comment]
All is checked and works
Custom Fee & Blacklist (fully complies with any configuration)
DVT coin also works

**Comment by belmix** [comment]
> Did you verify that everything still works if none of the new options are used?

All is checked and works
Custom Fee & Blacklist (fully complies with any configuration)
DVT coin also works

**Comment by J-A-M-P-S** [comment]
I still think is not good that the people can see the walletPassword in API output ?

walletpass

**Comment by belmix** [comment]
already wrote about this, configure the security of the node and separate the api and stratum in the settings

**Comment by belmix** [comment]
Closed due to lack of interest

**Pull request closed without merging**
