### PR TITLE
Added support for GhostRider hashing algorithm

### PR DESCRIPTION
**Pull request by noahtheprogrammer**
**Changes:**

1. Added GhostRider algorithm.
2. Implemented support for Raptoreum (RTM), a cryptocurrency forked from Dash.
3. Modified makefile and testing files to have support for GR's algorithm.

We have tested this code multiple times, and the pool is fully functional. Tell me if I need to modify anything in order to merge without any issues.

### CODE REVIEW

**Comment by noahtheprogrammer** [comment]
The build has failed because I accidentally removed the "M" suffix in front of the decimal for the donation fee.

**Comment by oliverw** [comment]
That's a ton of changes. Did you make sure that this does not break Monero etc?

**Comment by noahtheprogrammer** [comment]
> That's a ton of changes. Did you make sure that this does not break Monero etc?

I've sorted through the code, and we mainly just added an extra folder called cryptonote, in order to have a seperate space for modified algorithms GR uses. The only potential issue that could occur is how we changed line 8 in the Makefile and removed the 'jh.o` object. But other than that, all of the algorithms are in a new folder and none of the other coins or their algorithms have been changed.

**Comment by noahtheprogrammer** [comment]
@oliverw I'll double check again, just to be sure.

**Comment by riabikov** [comment]
@noahtheprogrammer While testing the pool, you don't get an error?
```
[E] [StatsRecorder] Npgsql.PostgresException (0x80004005): 42703: column "poolid" does not exist
```
What release did you use when adding the algorithm? 63?

**Comment by noahtheprogrammer** [comment]
We started added the algorithm after forming when miningcore had 2,283 commits. So, looking back, I believe it would be in between Releases 59 and 60.

**Comment by oliverw** [comment]
> @riabikov We started added the algorithm after forming when miningcore had 2,283 commits. So, looking back, I believe it would be in between Releases 59 and 60.

Makes sense. The problem was introduced with v60.

**Comment by oliverw** [comment]
> @oliverw I'll double check again, just to be sure.

So, all fine?

**Comment by noahtheprogrammer** [comment]
> > I'll double check again, just to be sure.
> 
> So, all fine?

@oliverw  It should be fine. It works on my machine, and I even added the `jh.o` back into the Makefile, in case any other algorithms were dependent on it.

**Comment by oliverw** [comment]
> > > I'll double check again, just to be sure.
> > 
> > 
> > So, all fine?
> 
> @oliverw It should be fine. It works on my machine, and I even added the `jh.o` back into the Makefile, in case any other algorithms were dependent on it.

Tests are still failing.

**Comment by oliverw** [comment]
Something is wrong with the libmultihash exports:

https://ci.appveyor.com/project/oliverw/miningcore/builds/41672483/job/ct2cuenges72a6ie

**Comment by noahtheprogrammer** [comment]
@oliverw I'll try to fix the lines. The strange thing is that it compiles and runs perfectly fine on my computer.

**Comment by oliverw** [comment]
> @oliverw I'll try to fix the lines. The strange thing is that it compiles and runs perfectly fine on my computer.

Would be cool.

**Comment by noahtheprogrammer** [comment]
@oliverw I'm not sure why, but it won't run on AppVeyor. I would recommend running it on your own computer, because I've loaded this software up on three different computers without any compilation errors now.

**Comment by oliverw** [comment]
> @oliverw I'm not sure why, but it won't run on AppVeyor. I would recommend running it on your own computer, because I've loaded this software up on three different computers without any compilation errors now.

It does not build on Github CI either: https://github.com/coinfoundry/miningcore/runs/4332449330?check_suite_focus=true

**Comment by noahtheprogrammer** [comment]
I'm not sure what could possibly be wrong. We're using this code for production and it works perfectly. The miner is getting accepted shares and everything. Below is proof that the pool is functioning.
pool

**Comment by chadouming** [comment]
> I'm not sure what could possibly be wrong. We're using this code for production and it works perfectly. The miner is getting accepted shares and everything. Below is proof that the pool is functioning. pool

Forgot to update the libmultihash in the runtime folder ?

**Comment by chadouming** [comment]
> I'm not sure what could possibly be wrong. We're using this code for production and it works perfectly. The miner is getting accepted shares and everything. Below is proof that the pool is functioning. pool

Must be missing something, gr.h and gr.c definitions of gr_hash does not match. One has the len parameter.

**Comment by noahtheprogrammer** [comment]
Does anyone have any ideas as to why this isn't functioning? On my original repo, it even passed the hashing tests.

**Comment by riabikov** [comment]
> Does anyone have any ideas as to why this isn't functioning? On my original repo, it even passed the hashing tests.

What exactly isn't working? Build validation failing? Or is mining itself not working? I have successfully built the project (not according to your fixes) and it works, although there is no way to check for 100%, there is not enough power to search for a block.

**Comment by BitWizJason** [comment]
The CI build is failing with this error `System.EntryPointNotFoundException : Unable to find an entry point named 'gr_export' in DLL 'libmultihash'.`

https://ci.appveyor.com/project/oliverw/miningcore/builds/41693343/job/xlltd9p2ryjh73n6/tests

I am not seeing an update to the libmultihash.dll in the runtime folder that corresponds to the changes. Its probably because the .gitignore was previously ignoring those folders. Take a look at my PR where I updated the .gitignore and added and updated version of libethhash.dll as an example https://github.com/coinfoundry/miningcore/pull/1010/files

If you pull in latest master of coinfoundry/miningcore you should get that .gitignore change. Which will then allow you to commit the updated dll. Or you could make the change to your branch directly as well.

**Comment by noahtheprogrammer** [comment]
@BitWizJason I've just changed the `.gitignore` file. Now, when I recompile on my developer machine, should the problem be solved?

**Comment by chadouming** [comment]
> Does anyone have any ideas as to why this isn't functioning? On my original repo, it even passed the hashing tests.

The ghostrider files need to be added to the miningcore dll project. They are in the Makefile, so they are compiled on linux, but not in the dll solution. You will also need to add any cryptoknight dependency.

**Comment by oliverw** [comment]
I would like to get this PR into the next release. :)

**Comment by noahtheprogrammer** [comment]
I know. I'm trying to get this fixed, but I'm new as to how miningcore works.

**Comment by BitWizJason** [comment]
@noahtheprogrammer I am going to pull down your branch this evening and see if I can resolve the issue.

**Comment by riabikov** [comment]
@BitWizJason I built the project with no errors, the pool is running on testnet, but encountered one error. I think this is the only problem that remains to be solved. Then I can add the complete code for adding the algorithm.

When the miner finds a solution to the block, we get an error:
```
Block 205298 submission failed with: bad-cb-founder-payment-not-found
```
The error condition is located here (206 line) - https://github.com/Raptor3um/raptoreum/blob/master/src/consensus/tx_verify.cpp

Cut from the code:
```
bool CheckTransaction(const CTransaction& tx, CValidationState &state, int nHeight, CAmount blockReward)
{
    bool allowEmptyTxInOut = false;
    if (tx.nType == TRANSACTION_QUORUM_COMMITMENT) {
        allowEmptyTxInOut = true;
    }

    // Basic checks that don't depend on any context
    if (!allowEmptyTxInOut && tx.vin.empty())
        return state.DoS(10, false, REJECT_INVALID, "bad-txns-vin-empty");
    if (!allowEmptyTxInOut && tx.vout.empty())
        return state.DoS(10, false, REJECT_INVALID, "bad-txns-vout-empty");
    // Size limits
    if (::GetSerializeSize(tx, SER_NETWORK, PROTOCOL_VERSION) > MAX_LEGACY_BLOCK_SIZE)
        return state.DoS(100, false, REJECT_INVALID, "bad-txns-oversize");
    if (tx.vExtraPayload.size() > MAX_TX_EXTRA_PAYLOAD)
        return state.DoS(100, false, REJECT_INVALID, "bad-txns-payload-oversize");

    // Check for negative or overflow output values
    CAmount nValueOut = 0;
    for (const auto& txout : tx.vout)
    {
        if (txout.nValue < 0)
            return state.DoS(100, false, REJECT_INVALID, "bad-txns-vout-negative");
        if (txout.nValue > MAX_MONEY)
            return state.DoS(100, false, REJECT_INVALID, "bad-txns-vout-toolarge");
        nValueOut += txout.nValue;
        if (!MoneyRange(nValueOut))
            return state.DoS(100, false, REJECT_INVALID, "bad-txns-txouttotal-toolarge");
    }

    // Check for duplicate inputs
    std::set<COutPoint> vInOutPoints;
    for (const auto& txin : tx.vin)
    {
        if (!vInOutPoints.insert(txin.prevout).second)
            return state.DoS(100, false, REJECT_INVALID, "bad-txns-inputs-duplicate");
    }

    if (tx.IsCoinBase())
    {
        size_t minCbSize = 2;
        if (tx.nType == TRANSACTION_COINBASE) {
            // With the introduction of CbTx, coinbase scripts are not required anymore to hold a valid block height
            minCbSize = 1;
        }
        if (tx.vin[0].scriptSig.size() < minCbSize || tx.vin[0].scriptSig.size() > 100)
            return state.DoS(100, false, REJECT_INVALID, "bad-cb-length");
		FounderPayment founderPayment = Params().GetConsensus().nFounderPayment;
		CAmount founderReward = founderPayment.getFounderPaymentAmount(nHeight, blockReward);
		int founderStartHeight = founderPayment.getStartBlock();
		//std::cout << "height=" << nHeight << ", reward=" << founderReward << endl;
		if(nHeight > founderStartHeight && founderReward && !founderPayment.IsBlockPayeeValid(tx,nHeight,blockReward)) {
			return state.DoS(100, false, REJECT_INVALID, "bad-cb-founder-payment-not-found");
		}
    }
    else
    {
        for (const auto& txin : tx.vin)
            if (txin.prevout.IsNull())
                return state.DoS(10, false, REJECT_INVALID, "bad-txns-prevout-null");
    }

    return true;
}
```

**Comment by noahtheprogrammer** [comment]
> @noahtheprogrammer I am going to pull down your branch this evening and see if I can resolve the issue.

@BitWizJason Cool. Just let me know when I need to accept the request.

**Comment by noahtheprogrammer** [comment]
I might close this pull request unless someone can fix the issues.

**Comment by oliverw** [comment]
I’ll have a look at it on Sunday

Oliver Weichhold
________________________________
Von: noahtheprogrammer ***@***.***>
Gesendet: Friday, December 3, 2021 9:07:38 PM
An: coinfoundry/miningcore ***@***.***>
Cc: Oliver Weichhold ***@***.***>; Mention ***@***.***>
Betreff: Re: [coinfoundry/miningcore] Added support for GhostRider hashing algorithm (PR #1005)


I might close this pull request unless someone can fix the issues.

**Comment by BitWizJason** [comment]
> I might close this pull request unless someone can fix the issues.

@noahtheprogrammer Give me until the end of the weekend to see what I can come up with please. Got busy the last couple of days at my day job with a major release 😁

**Comment by noahtheprogrammer** [comment]
@BitWizJason Nice! Hope the release went well.

**Comment by oliverw** [comment]
Hmm, apparently none of this has been tested under Windows. Most of this would probably be much better off to reside either in the `libcryptonote` project or preferably inside its own dedicated native library project (`libghostrider` ?).

**Comment by BitWizJason** [comment]
Thank you @noahtheprogrammer! So I sorted through quite a few errors while working to get libmultihash built on Windows. The last one that I ran into was that the function jh_hash is defined twice. Once in jh.c and once in c_jh.c (introduced with the cryptonote files). That could probably be resolved like @oliverw said by moving the ghostrider code and dependencies into its own library.

**Comment by noahtheprogrammer** [comment]
Ok. I might just close this pull request and redo everything properly on another fork of miningcore. Then, once I've verified it passes the tests, I'll open a new pull request with the better changes. Is that cool?

**Comment by oliverw** [comment]
> Ok. I might just close this pull request and redo everything properly on another fork of miningcore. Then, once I've verified it passes the tests, I'll open a new pull request with the better changes. Is that cool?

Totally. And please be assured that your PR is greatly appreciated, even though it could not be merged this time.

**Comment by noahtheprogrammer** [comment]
Closed because code is not usable. Will be added in another PR.

**Pull request closed without merging**
