### PR TITLE
Add support Ellaism

### PR DESCRIPTION
**Pull request by Konstantin35**
When testing is not unlocked wallet you commented out these lines https://github.com/Konstantin35/miningcore/blob/4f291c0c521193ccad2550617fe800b8569a0c5f/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs#L396-L397 and unlock wallet in parity

### CODE REVIEW

**Comment by oliverw** [comment]
@Konstantin35 Thanks for the PR. Did you test mining blocks on the coin's testnet and confirmed that it's working as intended?

**Comment by Konstantin35** [comment]
In test not tested in desktop mode all worked http://api.2zo.pw/ella1/blocks

**Comment by oliverw** [comment]
What's desktop mode?

**Comment by oliverw** [comment]
Or did you mean you've mined the block on the coin's mainnet?

**Comment by Konstantin35** [comment]
Sorry stupid translator

**Comment by oliverw** [comment]
@Konstantin35 Allright, great job 👍

**Pull request merged**
