### PR TITLE
Add straks support and some api calls #1

### PR DESCRIPTION
**Pull request by Kukks**
This PR is not ready.

Essentially it adds a new coin that uses masternodes and treasury funding.
I've also added a new api to fetch a single pool and renamed all endpoints to be api/pools/* to follow rest standards

### CODE REVIEW

**Comment by oliverw** [comment]
Great work so far. 👍

**Comment by Kukks** [comment]
For reference, here is the pool running my frontend based on my api server version:
http://5.189.159.254

**Comment by oliverw** [comment]
@Kukks Cool! So you did get the block submission errors sorted out?

**Comment by Kukks** [comment]
@oliverw Not yet, but I had a revelation in my sleep and am thinking I am using the main net treasury reward addresses instead of testnet.

**Comment by Kukks** [comment]
Testnet explorer for straks is at https://testnet.straks.info
Testnet treasury address is 93ASJtDuVYVdKXemH9BrtSMscznvsp9stD

**Comment by Kukks** [comment]
Removed hardcoded values in the strajs job to determine with treasury address to use. Unfortunately still getting the cb treasury error. @oliverw Any pointers?

**Comment by oliverw** [comment]
@Kukks No dice inspecting miner.cpp?

**Comment by Kukks** [comment]
@oliverw No luck :(  From what I saw,  They had the foudners reward system from Zcash and the masternodes payment from Dash.

Outgoing transaction is being constructed correctly from what I can tell:
```
{{
  "hash": "558b561b21fba83fe7967420e2cc2d0778909b75d60f1c26e220fcb5248d9ba1",
  "ver": 1,
  "vin_sz": 0,
  "vout_sz": 2,
  "lock_time": 0,
  "size": 76,
  "in": [],
  "out": [
    {
      "value": "9.50000000",
      "scriptPubKey": "OP_DUP OP_HASH160 026d4467d3eaec9ca1c7ba9257ceb1bc4573e73d OP_EQUALVERIFY OP_CHECKSIG"
    },
    {
      "value": "0.50000000",
      "scriptPubKey": "OP_HASH160 737c37ce6ef1ea0ca88cb947ecb9aee189c6ba23 OP_EQUAL"
    }
  ]
}}
```


The only thing I'm doubting is the treasury address not being created into a script correctly but I have no knowledge on that section at all.. It seemed like the Zcash implementation made sense. .

I moved the hardcoded treasury addresses to the config now since it is 1 account on testnet and 4 on mainnet.

Pool config I'm testing with:
```
{
      "treasuryAddresses": [
        "93ASJtDuVYVdKXemH9BrtSMscznvsp9stD"
      ],
      "id": "straks1",
      "enabled": true,
      "coin": {
        "type": "STAK"
      },
      "address": "t79SJCCTmhL5P9qWNsJWPPhX4UPyWhgKkZ",
      "rewardRecipients": [
        {
          "address": "t79SJCCTmhL5P9qWNsJWPPhX4UPyWhgKkZ",
          "percentage": 1.0
        }
      ],
      "blockRefreshInterval": 1000,
      "jobRebroadcastTimeout": 55,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "4500": {
          "listenAddress": "0.0.0.0",
          "difficulty": 1,
          "name": "1Difficulty",
          "varDiff": {
            "minDiff": 0.5,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        },
        "4501": {
          "listenAddress": "0.0.0.0",
          "difficulty": 10,
          "name": "10Difficulty",
          "varDiff": {
            "minDiff": 5,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        }
      },

      "daemons": [
        {
          "host": "127.0.0.1",
          "port": 19333,
          "user": "straks",
          "password": "straks"
        }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.5,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      }
    }
```

**Comment by Kukks** [comment]
@oliverw Any help is greatly appreciated. I feel like there is a tiny thing left out which is outside my knowledge.
They have this written on the straks repo description: 
```
Due to the unique combination of SegWit, treasury reward, miner reward and Masternode payments, as of this writing, mining software and pools do not yet support STRAKS' coinbasetxn configuration. The only way to mine at the moment is via STRAKS' wallet, as follows:
```

The only working pool for straks is a custom YIIMP coming from this commit `https://github.com/DeckerSU/yiimp/commit/baf855a4de8b9a6b55ff37723e6437ab643c8311`

**Comment by oliverw** [comment]
@Kukks If I was you I would open a ticket at the straks github repo and ask for clarification about the coinbase tx.

**Comment by oliverw** [comment]
@Kukks Any news on this?

**Comment by Kukks** [comment]
Nada.. I think the issue lies with the way the byte array is generated for
the treasury address in the  output transaction.

**Comment by oliverw** [comment]
One thing you could try is replacing FoundersAddressToScriptDestination with BitcoinUtils.AddressToDestination in https://github.com/coinfoundry/miningcore/pull/90/files#diff-0a125923aa9a7aeeb8ef8a37e5ded686R56

**Comment by Kukks** [comment]
I think I've tried that but will give it another go in a bit. :) I noticed
straks has a built in class cstraksaccount instead of the usual fork way of
having a cBitcoinAddress. Hopefully nothing is different in there though.

**Comment by ekamgit** [comment]
The scriptPubKey for the treasury you are generating is incorrect. You are removing too many bytes from the beginning of the hash and leaving an extra pair at the end.

If you compare your hash to one from a valid testnet transaction, you will see where the issue lies.

```
737c37ce6ef1ea0ca88cb947ecb9aee189c6ba23
f9737c37ce6ef1ea0ca88cb947ecb9aee189c6ba
```
As shown above, the first hash is shifted to the left and is incorrect.

To get the correct hash you need to decode the address from base58 and then remove the first byte (version) and the last 4 bytes (checksum).

**Comment by oliverw** [comment]
@ekamgit Of course! Great find! The reason for this is that <code>FoundersAddressToScriptDestination </code> was written for ZCash which uses two prefix-bytes.

**Comment by Kukks** [comment]
@ekamgit Thank you! I will test and review, hopefully we can close this soon. :)

**Comment by Kukks** [comment]
Updated and seems like block is being submitted fine now but I'm getting this now @oliverw 
```
[2017-11-27 11:32:29.3541] [I] [straks1] [Bitcoin Job Manager] New block 88373 detected
[2017-11-27 11:32:53.4491] [I] [straks1] [Bitcoin Job Manager] Submitting block 88373 [40c1cc55315a52989ac92f006d7add60c75fe612aa9500060c8c77d42ac775fb]
[2017-11-27 11:33:05.7751] [I] [straks1] [Bitcoin Job Manager] New block 88374 detected
[2017-11-27 11:33:05.7751] [W] [straks1] [Bitcoin Job Manager] Block 88373 submission failed because block was not found after submission
[2017-11-27 11:33:05.7788] [I] [straks1] [Pool] [0HL9LG075TUM9] Share accepted: D=0.5
[2017-11-27 11:33:06.8209] [I] [straks1] [Bitcoin Job Manager] Submitting block 88374 [9f33a13dfa04050c0392286bb7539aaef1b97a01a70e0dd58ec007df4c234c26]
[2017-11-27 11:33:06.8329] [W] [straks1] [Bitcoin Job Manager] Block 88374 submission failed because block was not found after submission
```

**Comment by oliverw** [comment]
Is there a blockchain explorer for the coin?

**Comment by Kukks** [comment]
https://testnet.straks.info

**Comment by oliverw** [comment]
1. Are your mined blocks visible there with the correct address in the coinbase (indeed mined by yourself)
2. Did you check <code>debug.log</code> inside the daemons data directory?

**Comment by Kukks** [comment]
Yup, my test address is https://testnet.straks.info/address/t79SJCCTmhL5P9qWNsJWPPhX4UPyWhgKkZ


```
2017-11-27 12:02:02 CreateNewBlock(): total size: 262 block weight: 940 txs: 0 fees: 0 sigops 400
2017-11-27 12:02:02 CheckBlock() : non-specific masternode payments 88957
2017-11-27 12:02:02 CheckBlock() : found payment[1|0] or payee[1|3QJmnh] nHeight 88957.
2017-11-27 12:02:02 CheckBlock() : non-specific masternode payments 88957
2017-11-27 12:02:02 CheckBlock() : found payment[1|0] or payee[1|3QJmnh] nHeight 88957.
2017-11-27 12:02:36 CheckBlock() : non-specific masternode payments 88957
2017-11-27 12:02:36 CheckBlock() : found payment[1|0] or payee[1|3QJmnh] nHeight 88957.
2017-11-27 12:02:36 UpdateTip: new best=000001013a4a21544c92759266b4e4562a71adf7ae2579bfce1b1d358d7b7fb5 height=88957 version=0x20000000 log2_work=37.124505 tx=89072 date='2017-11-27 12:02:34' progress=1.000000 cache=0.2MiB(906tx)
2017-11-27 12:02:36 ProcessNewBlock : ACCEPTED
2017-11-27 12:02:36 CreateNewBlock: Failed to detect masternode to pay
2017-11-27 12:02:36 CreateNewBlock(): total size: 262 block weight: 940 txs: 0 fees: 0 sigops 400
2017-11-27 12:02:36 CheckBlock() : non-specific masternode payments 88958
2017-11-27 12:02:36 CheckBlock() : found payment[1|0] or payee[1|3QJmnh] nHeight 88958.
2017-11-27 12:02:36 CheckBlock() : non-specific masternode payments 88958
2017-11-27 12:02:36 CheckBlock() : found payment[1|0] or payee[1|3QJmnh] nHeight 88958.
2017-11-27 12:02:42 CheckBlock() : non-specific masternode payments 88958
2017-11-27 12:02:42 CheckBlock() : found payment[1|0] or payee[1|3QJmnh] nHeight 88958.
2017-11-27 12:02:42 UpdateTip: new best=000001f29b0433a2bc3aa939efe2c29d427ad20ac1216c82e46e050f1f365037 height=88958 version=0x20000000 log2_work=37.124528 tx=89073 date='2017-11-27 12:02:36' progress=1.000000 cache=0.2MiB(907tx)
2017-11-27 12:02:42 AddToWallet cf0988a3bce4eecbf50e6fb19295df9214a6e062c63e27e05ae5722a40401c9e  new
2017-11-27 12:02:42 ProcessNewBlock : ACCEPTED
2017-11-27 12:02:43 CreateNewBlock: Failed to detect masternode to pay
2017-11-27 12:02:43 CreateNewBlock(): total size: 262 block weight: 940 txs: 0 fees: 0 sigops 400
2017-11-27 12:02:43 CheckBlock() : non-specific masternode payments 88959
2017-11-27 12:02:43 CheckBlock() : found payment[1|0] or payee[1|3QJmnh] nHeight 88959.
2017-11-27 12:02:43 CheckBlock() : non-specific masternode payments 88959
2017-11-27 12:02:43 CheckBlock() : found payment[1|0] or payee[1|3QJmnh] nHeight 88959.
```

**Comment by oliverw** [comment]
So submissions definitely succeeds but getblock using the block hash fails?

**Comment by Kukks** [comment]
Yes, just verified it

**Comment by oliverw** [comment]
That would indicate that the wrong block hash algorithm [is used](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinJob.cs#L342) and you need a variation of [this](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinProperties.cs#L53) using the correct algorithm.

**Comment by Kukks** [comment]
@oliverw Ok, any idea where I can find the corresponding code in the coin source?

**Comment by oliverw** [comment]
@Kukks I'd ask @ekamgit straight away. He possibly knows which algorithm is used for computing the blockhash.

**Comment by Kukks** [comment]
Hmm yes, @ekamgit, care yo jump in once more? :)
Currently it's mapped to this:
`BitcoinCoinProperties(double shareMultiplier, IHashAlgorithm coinbaseHasher, IHashAlgorithm headerHasher,
            IHashAlgorithm blockHasher, IHashAlgorithm posblockHasher = null) `
`BitcoinCoinProperties(Math.Pow(2, 8), sha256D, lyra2Rev2, sha256DReverse);`

**Comment by ekamgit** [comment]
https://github.com/straks/straks/blob/33a05613011514b35b09523fffcb4514b74f89c5/src/primitives/block.cpp#L16

**Comment by oliverw** [comment]
@ekamgit But that's the algo used for [the blockheader](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinJob.cs#L304), @Kukks was referring to the algo used for [computing the block hash](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinJob.cs#L342)

**Comment by Kukks** [comment]
@oliverw @ekamgit  
Perhaps until we can get this clarified from @ekamgit, I can go a different approach for now and use the walletnotify/blocknotify to check if I have received the funds?

**Comment by oliverw** [comment]
@Kukks Bad idea. The pipeline is built around the idea that at the end of processing a share it is know whether it's just a share or a block candidate.

**Comment by Kukks** [comment]
@oliverw I think I got it! It was an lyra2rev2 with a reverse on !t. I'll test it out a bit and see how it runs and let you know

**Comment by Kukks** [comment]
@oliverw I can confirm it works with the testnet. :)

**Comment by oliverw** [comment]
@Kukks Cool that you've figured it out Andrew! 👍

**Comment by oliverw** [comment]
@Kukks My compliment, the implemenation couldn't be much cleaner if I did it myself. You truely understood how everything works 👍

**Comment by ekamgit** [comment]
Will you be incorporating full segwit implementation for STRAKS at any stage?

**Comment by Kukks** [comment]
@ekamgit I saw that there is already some handling of segwit in the core pool. Can you confirm @oliverw? 

P.S. Sorry for those hotifxes I saw you do after my branch oliver. :P

**Pull request merged**
