### PR TITLE
Build enhancements

### PR DESCRIPTION
**Pull request by snoby**
* Used .net docker images suggested by @jon4hz.
* Added the parallel job build flag to speed build up

### CODE REVIEW

**Comment by snoby** [comment]
A pull request with the enhancements by @jon4hz 
I also added the parallel jobs build to the make command in the build-libs-linux.sh file.  I debated over whether to add this or not.  It could make tracking down a build issue slightly more difficult, but it does increase the build speed quite substantially which is a 'quality of life' improvement.  I'm ok to take the parallel job enhancement out if desired... or maybe make an environmental flag variable that turns it off and on...

**Comment by oliverw** [comment]
The parallel stuff has to be optional. Build times are not a priority since mining pools are not updated that frequently to keep downtimes in check.

**Comment by snoby** [comment]
i agree with you, definitely needs to be reworked.

**Comment by oliverw** [comment]
Is this still being worked on?

**Comment by snoby** [comment]
I opened a new PR with just the dockerfile modified.

https://github.com/oliverw/miningcore/pull/1502

**Pull request closed without merging**
