### PR TITLE
Fixed memory leak with growing stratum connections

### PR DESCRIPTION
**Pull request by kabilanvk**
There was a leak in memory after onboarding 3k miners since the stale connection objects were lingering around.

### CODE REVIEW

**Comment by oliverw** [comment]
I fail to see what memory leak the code is supposed to fix. The entire EthereumJob object is de-referenced and thus GC'ed anyway.

**Comment by kabilanvk** [comment]
> EthereumJob
Before its cleaning the EthereumJob the collection inside grows faster and ended up growing memory. I've attached a memory dump screenshot where you can see them. 
2021-09-23 20_15_47-Clipboard

**Comment by oliverw** [comment]
> > Before its cleaning the EthereumJob the collection inside grows faster and ended up growing memory. I've attached a memory dump screenshot where you can see them.

1. You talk about stale connections but the change affects a Job object owned by the JobManager. 
2. Looking at the dump the accumulated size of the `HashSet<string>` appears to be neglectable compared to the accumulated size of the `StratumClient` instances. Either there's a look elsewhere with the StratumClient instances or you had 32k concurrent miners at the time of the snapshot!?

**Comment by kabilanvk** [comment]
> > > Before its cleaning the EthereumJob the collection inside grows faster and ended up growing memory. I've attached a memory dump screenshot where you can see them.
> 
> 1. You talk about stale connections but the change affects a Job object owned by the JobManager.
> 2. Looking at the dump the accumulated size of the `HashSet<string>` appears to be neglectable compared to the accumulated size of the `StratumClient` instances. Either there's a look elsewhere with the `StratumClient` instances or you had 32k concurrent miners at the time of the snapshot!?

The connection objects don't get cleaned up by GC because it's still referenced by EthereumJob. I had only 2.7K miners at the max but stale connections are accumulated over time.

**Comment by oliverw** [comment]
> > > > Before its cleaning the EthereumJob the collection inside grows faster and ended up growing memory. I've attached a memory dump screenshot where you can see them.
> > 
> > 
> > 
> > 1. You talk about stale connections but the change affects a Job object owned by the JobManager.
> > 2. Looking at the dump the accumulated size of the `HashSet<string>` appears to be neglectable compared to the accumulated size of the `StratumClient` instances. Either there's a look elsewhere with the `StratumClient` instances or you had 32k concurrent miners at the time of the snapshot!?
> 
> The connection objects don't get cleaned up by GC because it's still referenced by EthereumJob. I had only 2.7K miners at the max but stale connections are accumulated over time.

Ok, understood. But this should only become a real problem if your EthereumJob instances are extremely long lived which can only happen if the Job Manager does not receive new blocks from the chain. Otherwise EthereumJob instances should be eventually phased out by subsequent job updates. Just trying to figure out how this can become a problem in the first place.

**Pull request closed without merging**
