### PR TITLE
X16RT hash

### PR DESCRIPTION
**Pull request by Konstantin35**
Currencies on the algorithm X16RT

Name: Veil (VEIL)
Github: https://github.com/Veil-Project/veil
Website: https://veil-project.com/
Coinmarketcap: https://coinmarketcap.com/currencies/veil/

Name: GINcoin (GIN)
Github: https://github.com/GIN-coin/gincoin-core
Website: https://gincoin.io/
Coinmarketcap: https://coinmarketcap.com/currencies/gincoin/

### CODE REVIEW

**Comment by oliverw** [comment]
Good Job @Konstantin35. The only minor thing thats missing is a unit test. Could you add one to https://github.com/coinfoundry/miningcore/blob/master/src/Miningcore.Tests/Crypto/HashingTests.cs

**Comment by oliverw** [comment]
@Konstantin35 Test is failing.

**Comment by Konstantin35** [comment]
> 
> 
> @Konstantin35 Test is failing.

Yes failure but on the bullet everything works.
I will look for a reason if you got any ideas let me know

**Comment by oliverw** [comment]
@Konstantin35 Why did you close it? It was just the Unit test that needed fixing.

**Comment by Konstantin35** [comment]
I spent two days trying to correct the thought that the problem in X16RT.c I couldn't fix lack of knowledge.
If you can help, I'll be glad.

**Pull request closed without merging**
