### PR TITLE
Could you merge a Globaltoken(GLT) support by MiningCore?

### PR DESCRIPTION
**Pull request by jeong760**
Dears,

I've created a PR for Globaltoken(GLT) support by MiningCore

Regards,
John Ahn

### CODE REVIEW

**Comment by oliverw** [comment]
Did you test the coin in production?

**Comment by oliverw** [comment]
Could you please correct the indentation using spaces to match the existing code base?

**Comment by jeong760** [comment]
@oliverw ok. I will modification them

**Comment by jeong760** [comment]
@oliverw yes I've test it on my production pool. And there is no problem

**Comment by jeong760** [comment]
Done

**Pull request merged**
