### PR TITLE
VarDiff Bugs Fixed and Redesign

### PR DESCRIPTION
**Pull request by shtse8**
I hope this PR can help this project. But I am not familiar with C#. Please kindly review my code and optimize it.

1. Cancelled periodic VarDiff updates.
2. Added Timer after each submit for checking if the diff is too high.
3. VarDiffManager always take the current round of submit into account. But will not add the current round until submit. So update can be called any time.
4. Manager will be created once connected.
5. Time will be `double` instead of `long` for accuracy.
6. Avoided using `toArray()`, it seems array copy is not good for performance. just loop the buffer and get the sum.
7. Simplify the coding of calculating newdiff.
 
I have tested the following configs. Everything seems fine.
```
               "difficulty": 128,
                "varDiff": {
                    "minDiff": 8,
                    "maxDiff": null,
                    "targetTime": 30,
                    "retargetTime": 5,
                    "variancePercent": 30
                }
```
```
               "difficulty": 128,
                "varDiff": {
                    "minDiff": 8,
                    "maxDiff": null,
                    "targetTime": 5,
                    "retargetTime": 1,
                    "variancePercent": 30
                }
```
```
               "difficulty": 128,
                "varDiff": {
                    "minDiff": 8,
                    "maxDiff": null,
                    "targetTime": 60,
                    "retargetTime": 60,
                    "variancePercent": 30
                }
```

### CODE REVIEW

**Comment by shtse8** [comment]
I am trying with Nicehash.
The last dead is this PR update.

image

The performance seems better now. (Green is good, Red is bad.)

**Comment by shtse8** [comment]
I know it still have some problems. But I don't know how to fix it.
1. how to update the diff instantly instead of next new job or `updateVarDiff(client)`? Should we put the following code in `OnSubmitAsync`?
```
 if (client.Context.ApplyPendingDifficulty())
                        client.Notify(BitcoinStratumMethods.SetDifficulty, new object[] {client.Context.Difficulty});
```
2. I don't know if my timer is correct or not. don't familiar with C#.

**Comment by oliverw** [comment]
Could you [squash](https://gist.github.com/patik/b8a9dc5cd356f9f6f980) all three commits into one. Makes it easier to follow the changes.

**Comment by shtse8** [comment]
Sure. I have created a new branch called vardiff in my fork. Then I run the following commands.  But I got an error. Is my command correct? 
```
root@mining:~/dev/miningcore# git reset --soft HEAD~3
root@mining:~/dev/miningcore# git commit -m "VarDiff redesign and bug fix."
[master b3eb04b] VarDiff Redesign and Bug Fix
 5 files changed, 1053 insertions(+), 980 deletions(-)
 create mode 100644 src/MiningCore/Util/CircularDoubleBuffer.cs
root@mining:~/dev/miningcore# git push origin +vardiff
error: src refspec vardiff does not match any.
error: failed to push some refs to 'https://github.com/shtse8/miningcore'
```

**Comment by oliverw** [comment]
You probably need to sync your branch with origin first.

**Comment by shtse8** [comment]
Done. Is it okay now?

**Pull request merged**
