### PR TITLE
X13

### PR DESCRIPTION
**Pull request by Konstantin35**
Add X13

### CODE REVIEW

**Comment by oliverw** [comment]
You've added a binding to X13 to LibMultiHash.cs but the native libmultihash does not even export the algorithm 😏

**Comment by oliverw** [comment]
Why does the PR contain commits from your previous ELLA PR?

**Comment by Konstantin35** [comment]
I don't know why can that not so made

**Comment by Konstantin35** [comment]
I added Musicoin but not yet tested

**Comment by oliverw** [comment]
@Konstantin35 Could you please be so kind and ensure that your PR only contains commits related to the PR?

**Comment by oliverw** [comment]
@Konstantin35 What's the current status of this PR?

**Pull request closed without merging**
